Class: ""
Displays:
  - Alpha: 0.5
    Cell Size: 1
    Class: rviz/Grid
    Color: 160; 160; 160
    Enabled: true
    Line Style:
      Line Width: 0.029999999329447746
      Value: Billboards
    Name: Grid
    Normal Cell Count: 0
    Offset:
      X: 0
      Y: 0
      Z: 0
    Plane: XY
    Plane Cell Count: 30
    Reference Frame: <Fixed Frame>
    Value: true
  - Alpha: 1
    Autocompute Intensity Bounds: true
    Autocompute Value Bounds:
      Max Value: 10
      Min Value: -10
      Value: true
    Axis: Z
    Channel Name: intensity
    Class: rviz/LaserScan
    Color: 255; 255; 255
    Color Transformer: Intensity
    Decay Time: 0
    Enabled: true
    Invert Rainbow: false
    Max Color: 255; 255; 255
    Min Color: 0; 0; 0
    Name: LaserScan
    Position Transformer: XYZ
    Queue Size: 10
    Selectable: true
    Size (Pixels): 3
    Size (m): 0.009999999776482582
    Style: Flat Squares
    Topic: /scan
    Unreliable: false
    Use Fixed Frame: true
    Use rainbow: true
    Value: true
  - Alpha: 0.699999988079071
    Class: rviz/Map
    Color Scheme: map
    Draw Behind: false
    Enabled: true
    Name: Map
    Topic: /map
    Unreliable: false
    Use Timestamp: false
    Value: true
  - Class: rviz/TF
    Enabled: true
    Frame Timeout: 15
    Frames:
      All Enabled: true
      base_footprint:
        Value: true
      laser:
        Value: true
      map:
        Value: true
      odom:
        Value: true
    Marker Alpha: 1
    Marker Scale: 1
    Name: TF
    Show Arrows: true
    Show Axes: true
    Show Names: true
    Tree:
      map:
        odom:
          base_footprint:
            laser:
              {}
    Update Interval: 0
    Value: true
  - Angle Tolerance: 0.10000000149011612
    Class: rviz/Odometry
    Covariance:
      Orientation:
        Alpha: 0.5
        Color: 255; 255; 127
        Color Style: Unique
        Frame: Local
        Offset: 1
        Scale: 1
        Value: true
      Position:
        Alpha: 0.30000001192092896
        Color: 204; 51; 204
        Scale: 1
        Value: true
      Value: false
    Enabled: false
    Keep: 100
    Name: Odometry
    Position Tolerance: 0.10000000149011612
    Queue Size: 10
    Shape:
      Alpha: 1
      Axes Length: 1
      Axes Radius: 0.10000000149011612
      Color: 255; 25; 0
      Head Length: 0.30000001192092896
      Head Radius: 0.10000000149011612
      Shaft Length: 1
      Shaft Radius: 0.05000000074505806
      Value: Arrow
    Topic: /odom
    Unreliable: false
    Value: false
  - Alpha: 1
    Class: rviz/RobotModel
    Collision Enabled: false
    Enabled: true
    Links:
      All Links Enabled: true
      Expand Joint Details: false
      Expand Link Details: false
      Expand Tree: false
      Link Tree Style: Links in Alphabetic Order
      base_footprint:
        Alpha: 1
        Show Axes: false
        Show Trail: false
        Value: true
      laser:
        Alpha: 1
        Show Axes: false
        Show Trail: false
        Value: true
    Name: rviz/RobotModel
    Robot Description: robot_description
    TF Prefix: ""
    Update Interval: 0
    Value: true
    Visual Enabled: true
Enabled: true
Global Options:
  Background Color: 48; 48; 48
  Default Light: true
  Fixed Frame: map
  Frame Rate: 30
Name: root
Tools:
  - Class: rviz/MoveCamera
  - Class: rviz/Interact
    Hide Inactive Objects: true
  - Class: rviz/Select
  - Class: rviz/SetInitialPose
    Theta std deviation: 0.2617993950843811
    Topic: initialpose
    X std deviation: 0.5
    Y std deviation: 0.5
  - Class: rviz/SetGoal
    Topic: goal
  - Class: rviz/MoveCamera
  - Class: rviz/Interact
    Hide Inactive Objects: true
  - Class: rviz/Select
  - Class: rviz/SetInitialPose
    Theta std deviation: 0.2617993950843811
    Topic: initialpose
    X std deviation: 0.5
    Y std deviation: 0.5
  - Class: rviz/SetGoal
    Topic: goal
Value: true
Views:
  Current:
    Class: rviz/Orbit
    Distance: 3.771043300628662
    Enable Stereo Rendering:
      Stereo Eye Separation: 0.05999999865889549
      Stereo Focal Distance: 1
      Swap Stereo Eyes: false
      Value: false
    Field of View: 0.7853981852531433
    Focal Point:
      X: 0
      Y: 0
      Z: 0
    Focal Shape Fixed Size: true
    Focal Shape Size: 0.05000000074505806
    Invert Z Axis: false
    Name: Current View
    Near Clip Distance: 0.009999999776482582
    Pitch: 1.340397834777832
    Target Frame: <Fixed Frame>
    Yaw: 3.1435811519622803
  Saved: ~
